spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    com.tastefinder: DEBUG
    org.springframework: INFO

# 开发环境使用的高德API密钥（请替换为你的密钥）
amap:
  key: 431faeae95f61be3faa8ac06a599fe27
  secret: your-dev-amap-secret

